version: 3
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network
  mysql:
    image: mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vacations
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_USER: vacations-api
      MYSQL_USER_PASSWORD: /run/secrets/mysql_user_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - mysqldata:/var/lib/mysql/

secrets:
  mysql_root_password:
    external: true
  mysql_user_password:
    external: true

networks:
  app-network:
    external: true

volumes:
  mysqldata:
    driver: local
