spring:
  profiles:
    active: development
  main:
    banner-mode: off
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    web.pageable.max-page-size: 100
    rest.max-page-size: 100
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://iperka.eu.auth0.com/
  jpa.open-in-view: false
auth0:
  audience: https://api.iperka.com/vacations/
  domain: https://iperka.eu.auth0.com/
springdoc:
  api-docs.path: /openapi/v3
  show-actuator: true
  swagger-ui:
    url: /openapi/v3/
    layout: BaseLayout
    oauth2RedirectUrl: http://localhost:8080/static/oauth2-redirect.html
---
spring:
  config.activate.on-profile: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:vacations-development
    driverClassName: org.h2.Driver
    username: sa
    password:
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
---
spring:
  config.activate.on-profile: production
  devtools:
    add-properties: false
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: ${DATASOURCE_DRIVER}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}
springdoc:
  api-docs.enabled: ${API_DOCS_ENABLED:false}
  # Requires API_DOCS_ENABLED
  swagger-ui.enabled: ${SWAGGER_UI_ENABLED:false}
auth0:
  audience: ${AUTH0_AUDIENCE:https://api.iperka.com/vacations/}
  domain: ${AUTH0_DOMAIN:https://iperka.eu.auth0.com/}