spring:
  profiles:
    active: development
  main:
    banner-mode: off
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    web.pageable.max-page-size: ${REST_MAX_PAGE_SIZE:100}
    rest.max-page-size: ${REST_MAX_PAGE_SIZE:100}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.domain}
  jpa.open-in-view: false
auth0:
  audience: ${AUTH0_AUDIENCE:https://api.iperka.com/vacations/}
  domain: ${AUTH0_DOMAIN:https://iperka.eu.auth0.com/}
springdoc:
  api-docs.path: ${API_DOCS_PATH:/openapi/v3}
  show-actuator: ${API_DOCS_SHOW_ACTUATOR:false}
  use-management-port: false
  default-produces-media-type: application/json
  produces-to-match:
    - application/json
  swagger-ui:
    url: ${SWAGGER_API_DOCS_PATH:/openapi/v3}
    layout: BaseLayout
    oauth2RedirectUrl: ${SWAGGER_UI_OAUTH2_REDIRECT_URL:http://localhost:8080/oauth2-redirect.html}
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
server.error.whitelabel.enabled: false
---
spring:
  config.activate.on-profile: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:vacations-development
    driverClassName: org.h2.Driver
    username: sa
    password:
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
---
spring:
  config.activate.on-profile: production
  devtools:
    add-properties: false
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: ${DATASOURCE_DRIVER}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}
springdoc:
  api-docs.enabled: ${API_DOCS_ENABLED:false}
  # Requires API_DOCS_ENABLED
  swagger-ui.enabled: ${SWAGGER_UI_ENABLED:false}
