spring:
  profiles:
    active: development
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: MY_ISSUER_URL
auth0:
  audience: MY_AUDIENCE_URL
---
spring:
  config.activate.on-profile: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:vacations-development
    driverClassName: org.h2.Driver
    username: sa
    password:
---
spring:
  config.activate.on-profile: production
  devtools:
    add-properties: false
