spring:
  profiles:
    active: development
  main:
    banner-mode: off
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  data:
    web.pageable.max-page-size: 100
    rest.max-page-size: 100
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://iperka.eu.auth0.com/
  jpa.open-in-view: false
auth0:
  audience: https://api.iperka.com/vacations/
---
spring:
  config.activate.on-profile: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:vacations-development
    driverClassName: org.h2.Driver
    username: sa
    password:
---
spring:
  config.activate.on-profile: production
  devtools:
    add-properties: false
