spring:
  profiles:
    active: development
  banner:
    location: classpath:/banner.txt
  main:
    banner-mode: console
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    web.pageable:
      max-page-size: ${REST_MAX_PAGE_SIZE:100}
    rest.max-page-size: ${REST_MAX_PAGE_SIZE:100}
  mongodb.embedded.version: 3.2.2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.domain}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:myUser}
    password: ${MAIL_PASSWORD:myPassword}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLED:true}
auth0:
  audience: ${AUTH0_AUDIENCE:https://api.iperka.com/vacations/}
  domain: ${AUTH0_DOMAIN:https://iperka.eu.auth0.com/}
  clientId: ${AUTH0_CLIENT_ID:MY_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET:MY_CLIENT_SECRET}
oneSignal:
  appId: ${ONE_SIGNAL_APP_ID:MY_APP_ID}
  apiKey: ${ONE_SIGNAL_API_KEY:MY_API_KEY}
  enabled: ${ONE_SIGNAL_ENABLED:false}
google.recaptcha.secret: ${GOOGLE_RECAPTCHA_SECRET:reCAPTCHA_site_secret}
springdoc:
  api-docs.path: ${API_DOCS_PATH:/openapi/v3}
  show-actuator: ${API_DOCS_SHOW_ACTUATOR:false}
  use-management-port: false
  default-produces-media-type: application/json
  produces-to-match:
    - application/json
  swagger-ui:
    url: ${SWAGGER_API_DOCS_PATH:/openapi/v3}
    layout: BaseLayout
    oauth2RedirectUrl: ${SWAGGER_UI_OAUTH2_REDIRECT_URL:http://localhost:8080/oauth2-redirect.html}
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
server:
  servlet.context-path: ${SERVER_SERVLET_CONTEXT_PATH:/}
  error.whitelabel.enabled: false
api.serverUrl: ${API_SERVER_URL:https://api.vacations.iperka.com/v1/}
mail:
  from:
    address: ${MAIL_FROM_ADDRESS:no-reply@iperka.com}
    name: ${MAIL_FROM_NAME:iperka}
---
spring:
  config.activate.on-profile: test
  main:
    banner-mode: off
  # The embedded testing server is not an official mongodb so it's suggested to use the Atlas database
  data:
    mongodb:
      database: ${MONGODB_DATABASE:vacations-api-test}
      uri: ${MONGODB_URI:mongodb://localhost:27017/}
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
---
spring:
  config.activate.on-profile: development
  data:
    mongodb:
      database: ${MONGODB_DATABASE:vacations-api-development}
      uri: ${MONGODB_URI:mongodb://localhost:27017/}
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
---
spring:
  config.activate.on-profile: production
  devtools:
    add-properties: false
  data:
    mongodb:
      database: ${MONGODB_DATABASE:vacations-api-production}
      uri: ${MONGODB_URI:mongodb://localhost:27017/}
springdoc:
  api-docs.enabled: ${API_DOCS_ENABLED:false}
  # Requires API_DOCS_ENABLED
  swagger-ui.enabled: ${SWAGGER_UI_ENABLED:false}
